ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.bridge_supply_anomaly]
path = "out/BridgeSupplyTrap.sol/BridgeSupplyTrap.json"
response_contract = "0x419ca88c659626115d02e030d4ab138fe97cede3"
response_function = "respondWithSupplyAlert(address,uint256,uint256)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 10
private_trap = true
whitelist = ["0x5ef7e326Dd821fadfE039Af897DccA917616736A"]

